config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :turmas
  resources :registros
  devise_for :users
  resources :espetaculos
  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/espetaculo.rb
class Espetaculo < ApplicationRecord
end

app/models/registro.rb
class Registro < ApplicationRecord
    enum titulo: [:artistico, :pedagogico, :difusao]
    enum tipo: [:entrada, :saida]
    
    
    
    
    
    
    
    
    
end

app/models/turma.rb
class Turma < ApplicationRecord

    enum modulo: [:I, :II, :III, :IV, :Infantil]
    
    
    
    
    
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    
  has_many :turmas    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
      protect_from_forgery with: :exception
    
      before_action :configure_permitted_parameters, if: :devise_controller?

      protected

      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name])
      end
end

app/controllers/espetaculos_controller.rb
class EspetaculosController < ApplicationController
  before_action :set_espetaculo, only: [:show, :edit, :update, :destroy]

  # GET /espetaculos
  # GET /espetaculos.json
  def index
    @espetaculos = Espetaculo.all
  end

  # GET /espetaculos/1
  # GET /espetaculos/1.json
  def show
  end

  # GET /espetaculos/new
  def new
    @espetaculo = Espetaculo.new
  end

  # GET /espetaculos/1/edit
  def edit
  end

  # POST /espetaculos
  # POST /espetaculos.json
  def create
    @espetaculo = Espetaculo.new(espetaculo_params)

    respond_to do |format|
      if @espetaculo.save
        format.html { redirect_to @espetaculo, notice: 'Espetaculo was successfully created.' }
        format.json { render :show, status: :created, location: @espetaculo }
      else
        format.html { render :new }
        format.json { render json: @espetaculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /espetaculos/1
  # PATCH/PUT /espetaculos/1.json
  def update
    respond_to do |format|
      if @espetaculo.update(espetaculo_params)
        format.html { redirect_to @espetaculo, notice: 'Espetaculo was successfully updated.' }
        format.json { render :show, status: :ok, location: @espetaculo }
      else
        format.html { render :edit }
        format.json { render json: @espetaculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /espetaculos/1
  # DELETE /espetaculos/1.json
  def destroy
    @espetaculo.destroy
    respond_to do |format|
      format.html { redirect_to espetaculos_url, notice: 'Espetaculo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_espetaculo
      @espetaculo = Espetaculo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def espetaculo_params
      params.require(:espetaculo).permit(:nome, :atores, :diretor, :sonoplasta, :iluminador)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/registros_controller.rb
class RegistrosController < ApplicationController
  before_action :set_registro, only: [:show, :edit, :update, :destroy]

  # GET /registros
  # GET /registros.json
  def index
    @registros = Registro.all
  end

  # GET /registros/1
  # GET /registros/1.json
  def show
  end

  # GET /registros/new
  def new
    @registro = Registro.new
  end

  # GET /registros/1/edit
  def edit
  end

  # POST /registros
  # POST /registros.json
  def create
    @registro = Registro.new(registro_params)

    respond_to do |format|
      if @registro.save
        format.html { redirect_to @registro, notice: 'Registro was successfully created.' }
        format.json { render :show, status: :created, location: @registro }
      else
        format.html { render :new }
        format.json { render json: @registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registros/1
  # PATCH/PUT /registros/1.json
  def update
    respond_to do |format|
      if @registro.update(registro_params)
        format.html { redirect_to @registro, notice: 'Registro was successfully updated.' }
        format.json { render :show, status: :ok, location: @registro }
      else
        format.html { render :edit }
        format.json { render json: @registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registros/1
  # DELETE /registros/1.json
  def destroy
    @registro.destroy
    respond_to do |format|
      format.html { redirect_to registros_url, notice: 'Registro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registro
      @registro = Registro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registro_params
      params.require(:registro).permit(:dia, :titulo, :descricao, :tipo, :valor)
    end
end

app/controllers/turmas_controller.rb
class TurmasController < ApplicationController
  before_action :set_turma, only: [:show, :edit, :update, :destroy]
    
    before_action :authenticate_user!   
  # GET /turmas
  # GET /turmas.json
  def index
    @turmas = Turma.all
  end

  # GET /turmas/1
  # GET /turmas/1.json
  def show
  end

  # GET /turmas/new
  def new
    @turma = Turma.new
  end

  # GET /turmas/1/edit
  def edit
  end

  # POST /turmas
  # POST /turmas.json
  def create
    @turma = Turma.new(turma_params)

    respond_to do |format|
      if @turma.save
        format.html { redirect_to @turma, notice: 'Turma was successfully created.' }
        format.json { render :show, status: :created, location: @turma }
      else
        format.html { render :new }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turmas/1
  # PATCH/PUT /turmas/1.json
  def update
    respond_to do |format|
      if @turma.update(turma_params)
        format.html { redirect_to @turma, notice: 'Turma was successfully updated.' }
        format.json { render :show, status: :ok, location: @turma }
      else
        format.html { render :edit }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turmas/1
  # DELETE /turmas/1.json
  def destroy
    @turma.destroy
    respond_to do |format|
      format.html { redirect_to turmas_url, notice: 'Turma was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turma
      @turma = Turma.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turma_params
      params.require(:turma).permit(:nome, :modulo, :horario)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/espetaculos_helper.rb
module EspetaculosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registros_helper.rb
module RegistrosHelper
end

app/helpers/turmas_helper.rb
module TurmasHelper
end

app/views/espetaculos/_form.html.erb
<%= form_with(model: espetaculo, local: true) do |form| %>
  <% if espetaculo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(espetaculo.errors.count, "error") %> prohibited this espetaculo from being saved:</h2>

      <ul>
      <% espetaculo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :espetaculo_nome %>
  </div>

  <div class="field">
    <%= form.label :atores %>
    <%= form.number_field :atores, id: :espetaculo_atores %>
  </div>

  <div class="field">
    <%= form.label :diretor %>
    <%= form.number_field :diretor, id: :espetaculo_diretor %>
  </div>

  <div class="field">
    <%= form.label :sonoplasta %>
    <%= form.number_field :sonoplasta, id: :espetaculo_sonoplasta %>
  </div>

  <div class="field">
    <%= form.label :iluminador %>
    <%= form.number_field :iluminador, id: :espetaculo_iluminador %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/espetaculos/edit.html.erb
<h1>Editing Espetaculo</h1>

<%= render 'form', espetaculo: @espetaculo %>

<%= link_to 'Show', @espetaculo %> |
<%= link_to 'Back', espetaculos_path %>

app/views/espetaculos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Espetaculos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Atores</th>
      <th>Diretor</th>
      <th>Sonoplasta</th>
      <th>Iluminador</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @espetaculos.each do |espetaculo| %>
      <tr>
        <td><%= espetaculo.nome %></td>
        <td><%= espetaculo.atores %></td>
        <td><%= espetaculo.diretor %></td>
        <td><%= espetaculo.sonoplasta %></td>
        <td><%= espetaculo.iluminador %></td>
        <td><%= link_to 'Show', espetaculo %></td>
        <td><%= link_to 'Edit', edit_espetaculo_path(espetaculo) %></td>
        <td><%= link_to 'Destroy', espetaculo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Espetaculo', new_espetaculo_path %>

app/views/espetaculos/new.html.erb
<h1>New Espetaculo</h1>

<%= render 'form', espetaculo: @espetaculo %>

<%= link_to 'Back', espetaculos_path %>

app/views/espetaculos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @espetaculo.nome %>
</p>

<p>
  <strong>Atores:</strong>
  <%= @espetaculo.atores %>
</p>

<p>
  <strong>Diretor:</strong>
  <%= @espetaculo.diretor %>
</p>

<p>
  <strong>Sonoplasta:</strong>
  <%= @espetaculo.sonoplasta %>
</p>

<p>
  <strong>Iluminador:</strong>
  <%= @espetaculo.iluminador %>
</p>

<%= link_to 'Edit', edit_espetaculo_path(@espetaculo) %> |
<%= link_to 'Back', espetaculos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cia do Nó de Teatro</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container">
              <%= link_to "Cia do Nó", root_path, class:"navbar-brand"%>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item active"><%= link_to "Administrativo", root_path, class:"nav-link" %></li>
                  <li class="nav-item active"><%= link_to "Artístico", espetaculos_path, class:"nav-link" %></li>
                  <li class="nav-item active"><%= link_to "Pedagógico", turmas_path, class:"nav-link" %></li>
                  <li class="nav-item active"><%= link_to "Difusão", root_path, class:"nav-link" %></li>
                    <li class="nav-item active"><%= link_to "Livro Caixa", registros_path, class:"nav-link" %></li>
                </ul>
              </div>
              <ul class="navbar-nav justify-content-end">
                  <% if user_signed_in? %>
                    <%= link_to "Editar",  edit_user_registration_path, class: "btn btn-info" %>&nbsp;
                    <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
                  <% else %>
                      <%= link_to "Entrar",  new_user_session_path, class: "btn btn-success" %>&nbsp;
                      <%= link_to "Cadastar",  new_user_registration_path, class: "btn btn-primary" %>
                  <% end %>
                  
              </ul>    
          </div>
        </nav>
      
      <% flash.each do |name, message| %>
        <%= content_tag(:div, message, class:"btn btn-info #{name}") %>
      <% end %>
      
    <div class="container"> 
        <%= yield %>
    </div> 
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
    <% if user_signed_in? %>
        <h1 class="display-3">Olá, <%= current_user.name %></h1>
    <% else %>
        <h1 class="display-3">Olá!</h1>
    <% end %>
  <p class="lead">Seja bem-vindo ao sistema da Cia do Nó de Teatro.</p>
  <hr class="my-4">
  <p>Aqui você pode administrar a Cia. Artístico, pedagógico e difusão</p>
  <p class="lead">
    <%= link_to "Cadastre-se", root_path, class:"btn btn-primary" %>
  </p>
</div>

app/views/registros/_form.html.erb
<%= form_with(model: registro, local: true) do |form| %>
  <% if registro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(registro.errors.count, "error") %> prohibited this registro from being saved:</h2>

      <ul>
      <% registro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dia %>
    <%= form.date_select :dia, id: :registro_dia %>
  </div>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.select :titulo, Registro.titulos.keys %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao, id: :registro_descricao %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.select :tipo, Registro.tipos.keys %>
</div>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor, id: :registro_valor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/registros/edit.html.erb
<h1>Editing Registro</h1>

<%= render 'form', registro: @registro %>

<%= link_to 'Show', @registro %> |
<%= link_to 'Back', registros_path %>

app/views/registros/index.html.erb
<p id="notice"><%= notice %></p>

<center><h1>Registros</h1></center>

<table class="table">
  <thead>
    <tr>
      <th>Dia</th>
      <th>Titulo</th>
      <th>Descricao</th>
      <th>Tipo</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registros.each do |registro| %>
      <tr>
        <td><%= registro.dia %></td>
        <td><%= registro.titulo %></td>
        <td><%= registro.descricao %></td>
        <td><%= registro.tipo %></td>
        <td><%= registro.valor %></td>
        <td><%= link_to 'Show', registro %></td>
        <td><%= link_to 'Edit', edit_registro_path(registro) %></td>
        <td><%= link_to 'Destroy', registro, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registro', new_registro_path %>

app/views/registros/new.html.erb
<h1>New Registro</h1>

<%= render 'form', registro: @registro %>

<%= link_to 'Back', registros_path %>

app/views/registros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dia:</strong>
  <%= @registro.dia %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @registro.titulo %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @registro.descricao %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @registro.tipo %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @registro.valor %>
</p>

<%= link_to 'Edit', edit_registro_path(@registro) %> |
<%= link_to 'Back', registros_path %>

app/views/turmas/_form.html.erb
<%= form_with(model: turma, local: true) do |form| %>
  <% if turma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(turma.errors.count, "error") %> prohibited this turma from being saved:</h2>

      <ul>
      <% turma.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :turma_nome, class:"form-control" %>
  </div>
    
  <div class="row">

      <div class="col-6">
          <div class="form-group">
            <%= form.label :modulo %>
            <%= form.select :modulo, Turma.modulos.keys, class:"form-control custom-select" %>
          </div>
      </div>    
      <div class="col-6">
          <div class="form-group">
            <%= form.label :horario %>
            <%= form.time_select :horario, id: :turma_horario, class:"form-control"  %>
          </div>
      </div>    

  </div>    
    <%= form.submit "Cadastrar", class:"btn btn-primary" %>
    
<% end %>

app/views/turmas/edit.html.erb
<h1>Editing Turma</h1>

<%= render 'form', turma: @turma %>

<%= link_to 'Show', @turma %> |
<%= link_to 'Back', turmas_path %>

app/views/turmas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Turmas da Cia do Nó de Teatro</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Moódulo</th>
      <th>Horario</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @turmas.each do |turma| %>
      <tr>
        <td><%= turma.nome %></td>
        <td><%= turma.modulo %></td>
        <td><%= turma.horario.strftime("%H:%M") %></td>
        <td><%= link_to 'Visualizar', turma, class:"btn btn-outline-success" %>
        <%= link_to 'Editar', edit_turma_path(turma), class:"btn btn-outline-info"  %>
        <%= link_to 'Deletar', turma, method: :delete, class:"btn btn-outline-danger" , data: { confirm: "#{current_user.name}, você tem certeza que deseja deletar a turma #{turma.nome}?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<center><%= link_to 'Adicionar Nova Turma', new_turma_path, class:"btn btn-primary" %></center>

app/views/turmas/new.html.erb
<h1>Nova Turma</h1>

<%= render 'form', turma: @turma %>

<%= link_to 'Voltar', turmas_path %>

app/views/turmas/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <div class="col-4">
        <div class="card" style="width: 20rem;">
          <img class="card-img-top" src="..." alt="Card image cap">
          <div class="card-body">
            <h4 class="card-title"><strong>Turma: </strong><%= @turma.nome %></h4>
            <h5 class="card-text"><strong>Modulo: </strong><%= @turma.modulo %></h5>
            <p class="card-text"><strong>Horario: </strong><%= @turma.horario.strftime("%H:%M") %></p>  
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
    </div>

    <div class="col-8">
        <div class="card">
          <div class="card-body">
          
              <div class="card">
                  <div class="card-body">
                  </div>     
              </div>   
            
          </div>     
        </div>    
    </div>

</div>

  
<%= link_to 'Edit', edit_turma_path(@turma) %> |
<%= link_to 'Back', turmas_path %>